/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('@paraxe/vue')['Badge']
    Button: typeof import('@paraxe/vue')['Button']
    ButtonGroup: typeof import('@paraxe/vue')['ButtonGroup']
    Card: typeof import('@paraxe/vue')['Card']
    Container: typeof import('@paraxe/vue')['Container']
    Dialog: typeof import('@paraxe/vue')['Dialog']
    EmptyState: typeof import('@paraxe/vue')['EmptyState']
    Eyebrow: typeof import('@paraxe/vue')['Eyebrow']
    Heading: typeof import('@paraxe/vue')['Heading']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('@paraxe/vue')['Input']
    Pagination: typeof import('@paraxe/vue')['Pagination']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('@paraxe/vue')['Section']
    SectionHeader: typeof import('@paraxe/vue')['SectionHeader']
    Select: typeof import('@paraxe/vue')['Select']
    Sidebar: typeof import('@paraxe/vue')['Sidebar']
    SidebarGroup: typeof import('@paraxe/vue')['SidebarGroup']
    SidebarItem: typeof import('@paraxe/vue')['SidebarItem']
    Skeleton: typeof import('@paraxe/vue')['Skeleton']
    Stack: typeof import('@paraxe/vue')['Stack']
    Table: typeof import('@paraxe/vue')['Table']
    Text: typeof import('@paraxe/vue')['Text']
    Title: typeof import('@paraxe/vue')['Title']
    Toast: typeof import('@paraxe/vue')['Toast']
    Tooltip: typeof import('@paraxe/vue')['Tooltip']
  }
}
