/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('@paraxe/vue')['Badge']
    Button: typeof import('@paraxe/vue')['Button']
    ButtonGroup: typeof import('@paraxe/vue')['ButtonGroup']
    Card: typeof import('@paraxe/vue')['Card']
    Container: typeof import('@paraxe/vue')['Container']
    Dialog: typeof import('@paraxe/vue')['Dialog']
    Divider: typeof import('@paraxe/vue')['Divider']
    EmptyState: typeof import('@paraxe/vue')['EmptyState']
    Eyebrow: typeof import('@paraxe/vue')['Eyebrow']
    Grid: typeof import('@paraxe/vue')['Grid']
    Heading: typeof import('@paraxe/vue')['Heading']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('@paraxe/vue')['Input']
    Label: typeof import('@paraxe/vue')['Label']
    Pagination: typeof import('@paraxe/vue')['Pagination']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('@paraxe/vue')['Section']
    SectionHeader: typeof import('@paraxe/vue')['SectionHeader']
    Select: typeof import('@paraxe/vue')['Select']
    Sidebar: typeof import('@paraxe/vue')['Sidebar']
    SidebarGroup: typeof import('@paraxe/vue')['SidebarGroup']
    SidebarItem: typeof import('@paraxe/vue')['SidebarItem']
    Skeleton: typeof import('@paraxe/vue')['Skeleton']
    Stack: typeof import('@paraxe/vue')['Stack']
    Table: typeof import('@paraxe/vue')['Table']
    Text: typeof import('@paraxe/vue')['Text']
    Textarea: typeof import('@paraxe/vue')['Textarea']
    Toast: typeof import('@paraxe/vue')['Toast']
  }
}

// For TSX support
declare global {
  const Badge: typeof import('@paraxe/vue')['Badge']
  const Button: typeof import('@paraxe/vue')['Button']
  const ButtonGroup: typeof import('@paraxe/vue')['ButtonGroup']
  const Card: typeof import('@paraxe/vue')['Card']
  const Container: typeof import('@paraxe/vue')['Container']
  const Dialog: typeof import('@paraxe/vue')['Dialog']
  const Divider: typeof import('@paraxe/vue')['Divider']
  const EmptyState: typeof import('@paraxe/vue')['EmptyState']
  const Eyebrow: typeof import('@paraxe/vue')['Eyebrow']
  const Grid: typeof import('@paraxe/vue')['Grid']
  const Heading: typeof import('@paraxe/vue')['Heading']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Input: typeof import('@paraxe/vue')['Input']
  const Label: typeof import('@paraxe/vue')['Label']
  const Pagination: typeof import('@paraxe/vue')['Pagination']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Section: typeof import('@paraxe/vue')['Section']
  const SectionHeader: typeof import('@paraxe/vue')['SectionHeader']
  const Select: typeof import('@paraxe/vue')['Select']
  const Sidebar: typeof import('@paraxe/vue')['Sidebar']
  const SidebarGroup: typeof import('@paraxe/vue')['SidebarGroup']
  const SidebarItem: typeof import('@paraxe/vue')['SidebarItem']
  const Skeleton: typeof import('@paraxe/vue')['Skeleton']
  const Stack: typeof import('@paraxe/vue')['Stack']
  const Table: typeof import('@paraxe/vue')['Table']
  const Text: typeof import('@paraxe/vue')['Text']
  const Textarea: typeof import('@paraxe/vue')['Textarea']
  const Toast: typeof import('@paraxe/vue')['Toast']
}